apiVersion: v1
kind: Service
metadata:
  name: regexicon
  labels:
    app: regexicon
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      name: api
  selector:
    app: regexicon
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: regexicon
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: regexicon
    spec:
      containers:
        - name: regexicon
          image: lorcan/regex-candidates
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "2Mi"
            limits:
              memory: "4Mi"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: regexicon
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: regexicon.com
    http:
      paths:
      - path: /
        backend:
          serviceName: regexicon
          servicePort: api

