- hosts: candidates
  remote_user: core
  gather_facts: false
  roles:
    - defunctzombie.coreos-bootstrap
  tasks:
    - name: Add `candidates` systemd unit
      remote_user: root
      become: true
      copy: src=./system/candidates.service dest=/etc/systemd/system/candidates.service
    - name: Add `watchtower` systemd unit
      remote_user: root
      become: true
      copy: src=./system/watchtower.service dest=/etc/systemd/system/watchtower.service
    - name: Install `candidates` service
      remote_user: root
      become: true
      shell: >
        systemctl enable /etc/systemd/system/candidates.service
    - name: Install `watchtower` service
      remote_user: root
      become: true
      shell: >
        systemctl enable /etc/systemd/system/watchtower.service
    - name: Reload systemd servicesz
      remote_user: root
      become: true
      shell: >
        systemctl daemon-reload
    - name: Start `candidates` service
      remote_user: root
      become: true
      shell: >
        systemctl start candidates
    - name: Start `watchtower` service
      remote_user: root
      become: true
      shell: >
        systemctl start watchtower
