version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./script/update
      - run: ./script/test

# machine:
#   ghc:
#   version: 7.10.3
#   services:
#     - docker

# dependencies:
#   override:
#     - "true"
#   cache_directories:
#     - ./obj
# compile:
#   override:
#     - ./script/build
# test:
#   override:
#     - "true"

# deployment:
#   live:
#     branch: live
#     commands:
#       - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
#       - ./script/deploy
