version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: ./script/update
      - run: ./script/test
      - store_artifacts:
          path: ./obj/dist-newstyle/build/x86_64-linux/ghc-8.8.3/Matching-0.1.0.0/hpc/vanilla/html/
